### ISSUE TITLE
Q: AceTime with external database?

### ISSUE THREAD

**Issue by arkhipenko** [bxparks/AceTime#40]
Hi,
Not an issue, but rather a question:
Is it possible to run AceTime with an external tz db?
For instance, on esp32 chips? There is a flash filesystem that could be updated OTA without recompiling the code. 
For other MCUs - the DB could be on SD card.
Is it possible? Is it doable given current architecture even if it needs to be changed?

**Comment by arkhipenko** [comment]
Based on your design that should be a change to a couple of broker classes to source data from the files rather than program memory, correct?

**Comment by bxparks** [comment]
Yes, I think the `internal/Brokers.h` is the place to start. It did occurred to me that having the TZDB files in flash file or SD card could be an option, but:
1) I don't have any hardware where I can test this,
2) I am not familiar with the edge cases and limitations of an Arduino filesystem,
3) I'm not sure I understand the use case.

I thought for an ESP8266 and ESP32, the entire firmware can be flashed OTA, including the TZDB data under `src/ace_time/zonedb[x]`. On the ESP32, compiling in the entire TZDB zoneinfo data consumes only an additional ~33kB of flash, e.g. increasing the total firmware size from ~220kB to ~250kB. What would be the advantage of moving the TZ database offline to a filesystem?

The other problem with offloading the TZDB is that currently, I consider the `zonedb` and `zonedbx` data structures to be an implementation detail that is not guaranteed to have a stable ABI. If we offload the database, we have a versioning problem, where old AceTime must be able to read new TZDB database, and I'd rather not get into that mess unless there is a compelling reason for adding that complexity.

**Comment by arkhipenko** [comment]
It is true that ESPx chips support flashing entire firmware OTA. However, tz db is essentially data, and has little to do with code. If the format of the db does not change, versioning should not be a problem. ( I realize the key word in that statement is _should_)
It is all about product support and operationalizing the updates.  It is easier to operationalize pushing a data file then implementing the whole firmware production and OTA. Firmware updates would require a development resource + version control and testing, possibly production of multiple versions still supported, while data update could be outsourced to a support team and could be the same file(s) across all devices. 

As far as ABI is concerned - the brokers should provide a good abstraction layer if the tz structure does not change, no? 

Firmware size on ESP32 is routinely above 1 MB by the way.

**Comment by bxparks** [comment]
You make a good point about the operational cost of updating the firmware, versus updating just the TZ database. (I didn't realize that ESP32 firmware are often 1MB or larger, but I haven't used the ESP32 much because of its higher power consumption and cost.) Reducing the operational cost seems like a good problem to have for commercial product, since that means that it has high usage, but adding this functionality AceTime means that the development and operational cost would be transferred to **me**.

I may look into this feature in the future, because it's an interesting technical problem, and I have a bunch of ideas about various storage formats that I would love to try out. Some of those solutions may help with the versioning problem. The current internal representation of the TZ DB will probably change slightly in the future. A major change may happen in about 10-11 years, as I plan to roll out a Year 2100 version of AceTime. The Broker interface will help, but I suspect that that will require a few tweaks. Supporting an offline TZDB database will also require extensions to the various tools that I have checked under the `tools/` directory.

From my quick survey of the effort required to support this feature, I don't think it will become a priority in the near future, since I don't personally need it, and I'm not willing to do this much work for someone else's benefit. If someone is willing to pay for this work, that calculation may change. You can email me directly if that's your situation.

**Comment by arkhipenko** [comment]
I was not suggesting you do it for free. Just asking where to start - I might give it a try, maybe not. 
Will keep you posted. Would be good to have an estimate. 

Can we move this conversation to email? arkhipenko@hotmail.com
