### ISSUE TITLE
List timezone names

### ISSUE THREAD

**Issue by YarekTyshchenko** [bxparks/AceTime#51]
I'm trying to get a list of all timezone names, but struggling to understand the ZoneInfo name format:

```cpp
for (uint16_t n = 0; n < ace_time::zonedb::kZoneRegistrySize; n++) {
    auto a = ace_time::zonedb::kZoneRegistry[n];
    Serial.println(a->name);
}
```
This prints part of the name, but without the prefix/fragment.

```
22:3:56.584 -> Detroit
22:3:56.585 -> Bogota
22:3:56.586 -> Glace_Bay
```

How would I get to a list that contains full names like `Europe/London` ?

**Comment by bxparks** [comment]
Hi, You are almost there. What you didn't realize is that the zone names are encoded and compressed, so you need go through a helper class to reach into `ZoneInfo`:

```C++
for (uint16_t n = 0; n < ace_time::zonedb::kZoneRegistrySize; n++) {
    auto a = ace_time::zonedb::kZoneRegistry[n];

    BasicZone basicZone(a);
    basicZone.printNameTo(Serial);
    Serial.print(' ');
    basicZone.printShortNameTo(Serial);
    Serial.println();
}
```

It looks like I need to update the documentation for `BasicZone` and `ExtendedZone`:
https://github.com/bxparks/AceTime/blob/develop/docs/date_time_timezone.md#BasicZoneAndExtendedZone
I thought I did that when I recently refactored these classes, but looks like I totally forgot it. I will do so now.

Can I ask, why do you need to get the list of all the zones? For a menu perhaps?

**Comment by YarekTyshchenko** [comment]
>Can I ask, why do you need to get the list of all the zones? For a menu perhaps?

For a menu exactly. I plan on putting it in with wireless configuration (though I have a feeling that all 266 strings might be too much to display in a single list. Perhaps I could populate an incremental search list...)

I'm really impressed with this library, and the efforts you put in to reduce the memory usage!

**Comment by bxparks** [comment]
Thanks! I guess this library is a labor of love. There are so many things to work on.

With regards to the menu, I'm not sure what is the best way to handle that. The `zonedb::kZoneRegistry` has 266 zones, the `zonedbx::kZoneRegistry has  386 zones, and even larger, the `zonedbx::kZoneAndLinkRegistry has 593 entries. Should they be sorted alphabetically? Or by UTC offset? Or geographically? Should they be grouped by regions, or by country? It seems to be a hard problem.

Personally, I have only needed to select from a list of 4-6 timezones on my clocks. So I use a custom registry, as shown in some of my examples, and I just cycle through them sequentially. I don't know at this point how to handle the general case. Part of the difficulty is that the "appropriate" solution seems to depend on the UI being presented to the user. Unfortunately, the AceTime library currently does not offer much help with this problem. You will probably have to create an external list of timezones and handle the user interaction in the application code.

FYI, I just checked in some code to change the output of `TimeZone::printShortTo()`, `BasicZone::printShortNameTo(), and `ExtendedZone::PrintShortNameTo()`, so that underscore characters in the short zone names are replaced with spaces (e.g. "Los_Angeles" is now printed as "Los Angeles"). This seems more natural and readable.

If you want to chat further about menus and how to select from large lists, let's do it on the GitHub Discussions (https://github.com/bxparks/AceTime/discussions) that I just activated for this project.

**Comment by YarekTyshchenko** [comment]
Its an interesting problem. The list is too large work with from UX perspective. I was thinking of creating a smaller more generic list, but I wonder if there really is an optimal solution here.

I've created a discussion with some more specific details of my project
https://github.com/bxparks/AceTime/discussions/53

**Comment by YarekTyshchenko** [comment]
> FYI, I just checked in some code to change the output of TimeZone::printShortTo(), BasicZone::printShortNameTo(), and ExtendedZone::PrintShortNameTo(), so that underscore characters in the short zone names are replaced with spaces (e.g. "Los_Angeles" is now printed as "Los Angeles"). This seems more natural and readable. (The full canonical zone name remains unchanged, i.e. "America/Los_Angeles").

As long as `ZoneRegistrar::getZoneInfoForName(const char* name)` still parses it correctly, thats fine for me.
I guess I could also send ZoneIds together with the names, that might be more portable

**Comment by bxparks** [comment]
Yes, the full zone name will never be modified, because it is the unique key defined by IANA TZ DB. But if you have the ZoneId, I recommend using that, because its size is fixed (4-bytes), and looking up the TimeZone by ZoneId is 2-4X faster than ZoneName according to my benchmarks. The situation where you have to use the ZoneName is when the time zone is being defined from outside of AceTime.

I'm going to close this issue, and continue the discussion on GitHub Discussions.
